name: WGBuild
version: '${project.version}'
main: com.d4rkr34lm.wgbuild.WGBuild
api-version: 1.19
authors: [ D4rkr34lm, PrinzAutistimus ]
description: Tools for WarGear development

commands:
  trail:
    description: This Command is used to use the trail feature
  plot:
    description: This command is used to create a plot or, if standing inside a plot area, open the plots GUI
  tnt:
    description: This command is used to disable/enable tnt damage on a plot
  protect:
    description: This command is used to disable/enable cannon protection on a plot
  sl:
    description: This command is used to disable/enable stopLag on a plot
  ground:
    description: Pastes baseplate
    aliases: floor
  tb1:
    description: Pastes Tier I testblock
  tb2:
    description: Pastes Tier II testblock
  tb3:
    description: Pastes Tier III testblock
  tb3s:
    description: Paste Tier III testblock with shields
  frm1:
    description: Pastes Tier I frame
  frm2:
    description: Pastes Tier II frame
  frm3:
    description: Pastes Tier III frame
  tbm:
    description: Pastes MiniWarGear testblock
  frmm:
    description: Pastes MiniWarGear frame
